#pragma once

#include "rust/cxx.h"
#include <atomic>
#include <cstdint>
#include <memory>

#include <gst/gst.h>

// Platform video-plane hooks, implemented natively per-OS (gst_video_mac.mm / gst_video_win.cc).
// Elsewhere (Linux) there is no in-process overlay: the pipeline hands frames to waylandsink
// directly and these are no-ops.
#if defined(__APPLE__) || defined(_WIN32)
extern "C" guintptr livi_attach_view(guintptr parent, void** outView);
extern "C" void livi_remove_view(void* view);
extern "C" void livi_set_view_hidden(void* view, bool hidden);
extern "C" void livi_set_content_region(void* view, void* sink, double cropL,
    double cropT, double visW, double visH, double tierW, double tierH);
extern "C" void livi_set_backdrop(guintptr parent, double r, double g, double b);
#else
[[maybe_unused]] static guintptr livi_attach_view(guintptr parent, void** outView) {
  *outView = nullptr;
  return parent;
}
[[maybe_unused]] static void livi_remove_view(void*) {}
[[maybe_unused]] static void livi_set_view_hidden(void*, bool) {}
[[maybe_unused]] static void livi_set_content_region(void*, void*, double, double, double, double,
    double, double) {}
[[maybe_unused]] static void livi_set_backdrop(guintptr, double, double, double) {}
#endif

// One decode pipeline + its (optional) native overlay view. Torn down in the destructor, so a
// Rust-side UniquePtr<Player> drop is enough to free every GStreamer/native resource.
struct Player {
  GstElement* pipeline = nullptr;
  GstElement* appsrc = nullptr;
  GstElement* sink = nullptr;
  GstElement* glshader = nullptr;
  void* view = nullptr;
  // Set from the (streaming-thread) bus sync handler when the sink reports its output surface
  // is gone (e.g. the user closed a bare waylandsink window on a desktop with no
  // avio-compositor to prevent that). Torn down lazily by whoever next touches this player,
  // never from inside the bus callback itself (changing pipeline state there can deadlock).
  std::atomic<bool> dead{false};

  ~Player();
};

// Full definition generated by cxx into lib.rs.h, included (after this header) by every
// translation unit that also includes this one.
struct CodecSupport;

// `gv_` prefix: GStreamer/GLib own several bare global names we'd otherwise collide with
// (e.g. `gst_version(guint*, guint*, guint*, guint*)`). Definitions in gst_video.cc.
rust::String gv_version();
rust::Vec<CodecSupport> gv_probe_codecs();

std::unique_ptr<Player> gv_create_player(rust::Str codec, uint64_t handle);
void gv_start(Player& player);
bool gv_push_buffer(Player& player, rust::Slice<const uint8_t> data);
bool gv_is_dead(const Player& player);
void gv_set_visible(Player& player, bool visible);
void gv_set_content_region(Player& player, double crop_l, double crop_t, double vis_w,
    double vis_h, double tier_w, double tier_h);
void gv_set_gamma(Player& player, double gamma, double contrast, double gain_r, double gain_g,
    double gain_b);
void gv_stop(Player& player);

void gv_set_backdrop(uint64_t handle, double r, double g, double b);

#ifdef __linux__
void gv_run_host(rust::Str sock_path, rust::Str crash_path);
#endif
